### ISSUE TITLE
Configs/Training details for inpainting

### ISSUE THREAD

**Issue by ahmed1996said** [saiboxx/chexray-diffusion#2]
Dear Authors,
Great work on this project, thanks for making the code available.

Would it be possible to share the yaml config file for inpainting? And also can you give a quick summary of how you trained the LDM model for the inpainting task.

Thanks in advance!

**Comment by saiboxx** [comment]
Hi @ahmed1996said,

Thanks for your interest in our work and I apologize for my late response.

For doing inpainting no extra training is necessary. You can facilitate the standard LDMs like `cheff_diff_uncond.pt` paired with the autoencoder and super-resolution model.

You are entirely correct. The repository lacks an example for the inpainting task. 
The code already exists within the original LDM repo, which is the basis for our model but is rather difficult to read and interpret sometimes.

So here is a small toy example:

### Load model as usual

```
from cheff import CheffLDM

device = 'cuda'
sdm_path = 'trained_models/cheff_diff_uncond.pt'
ae_path = 'trained_models/cheff_autoencoder.pt'

cheff_ldm = CheffLDM(model_path=sdm_path, ae_path=ae_path, device=device)
```

### Prepare inputs

You will need the original target image (256x256px) and a binary mask (64x64px), where a `1` indicates that this area should be inpainted.

```
from torchvision.transforms.functional import to_tensor, resize
from PIL import Image

orig = Image.open('Path to original image')
orig = to_tensor(orig).cuda().unsqueeze(0)
orig = resize(orig, [256, 256])
orig = orig * 2 - 1

mask = Image.open('Path to mask').convert('L')
mask = to_tensor(mask).cuda().unsqueeze(0)
mask = resize(mask, [64, 64])
```

### Do inpainting "manually" over underlying code

Here, we load the DDIM sampler manually. This has the utility to directly supply a mask and an encoded original image.

```
from cheff.ldm.models.diffusion.ddim import DDIMSampler

# Encode original image via AE
orig_enc = cheff_ldm.model.encode_first_stage(orig).mode()

# Get the correct shape
shape = [
    cheff_ldm.model.model.diffusion_model.in_channels,
    cheff_ldm.model.model.diffusion_model.image_size,
    cheff_ldm.model.model.diffusion_model.image_size
]

ddim = DDIMSampler(cheff_ldm.model)

 img_new, _ = ddim.sample(
    100, # Denoising steps
    batch_size=1,
    shape=shape,
    eta=1.,
    verbose=False, 
    mask=mask, # Binary mask
    x0=orig_enc # Encoded original image
  )

# Decode new image to pixel space
 img_new = cheff_ldm.model.decode_first_stage(img_new)
```

### Save image

Save your hopefully amazing results.

```
from torchvision.transforms.functional import to_pil_image

img_new.clamp_(-1, 1)
img_new = (img_new + 1) / 2
to_pil_image(img_new.squeeze(0)).save('New Path')
```

I also might add the following as an example notebook in the next few days.
I hope I was able to help you.

Please let me know if you have any questions or run in any troubles.

Cheers,
Tobias

**Comment by ahmed1996said** [comment]
Hi Tobias,

Thanks a lot for the detailed response! I just have one small doubt-- why is the image multiplied by two and then subtracted by 1?
```
orig = orig * 2 - 1
```
 Thanks in advance.

**Comment by saiboxx** [comment]
The image is loaded as UINT8 by PIL (0-255 range). `to_tensor' converts the PIL image to a tensor with floats in range [0-1].
The 'orig * 2 - 1' further converts it into [-1,1], which is helpful for numerical stability and is a usual procedure in generative architectures.

The operation is reverted in `img_new = (img_new + 1) / 2`.

**Comment by ahmed1996said** [comment]
Okay, that makes sense. Thanks a lot!

**Comment by saiboxx** [comment]
I added a convenience method and an [example notebook](https://github.com/saiboxx/chexray-diffusion/blob/main/notebooks/02_cheff_inpainting.ipynb) for the inpainting task :)

Thus, I close the issue.
