### ISSUE TITLE
text2img model does not support gpu inference

### ISSUE THREAD

**Issue by haidog-yaqub** [saiboxx/chexray-diffusion#5]

**Comment by saiboxx** [comment]
The tokenized text embeddings were not properly transferred to the chosen device in the LDM base.
I fixed it with [d6d3ffe](https://github.com/saiboxx/chexray-diffusion/commit/d6d3ffebb07d210be776f9c673743f3f0f2dfd57) :hammer: .

Can you please confirm that the error is resolved at your end?

**Comment by haidog-yaqub** [comment]
> The tokenized text embeddings were not properly transferred to the chosen device in the LDM base. I fixed it with [d6d3ffe](https://github.com/saiboxx/chexray-diffusion/commit/d6d3ffebb07d210be776f9c673743f3f0f2dfd57) 🔨 .
> 
> Can you please confirm that the error is resolved at your end?

It works! Thank you!
