### ISSUE TITLE
FID Calculation

### ISSUE THREAD

**Issue by ahmed1996said** [saiboxx/chexray-diffusion#6]
Greetings!

I wanted to reproduce the results presented in the paper, can you provide more details on how the FID was calculated? 

For example, did you use the [Clean-FID](https://github.com/GaParmar/clean-fid) process, and was the network an InceptionV3 network? How many samples did you generate (10k?) ?

Thanks in advance! :)

**Comment by saiboxx** [comment]
Hi @ahmed1996said ,
Thanks for asking! 

The FID was computed using the [torchmetrics package](https://torchmetrics.readthedocs.io/en/stable/image/frechet_inception_distance.html) across 25k samples.
The same goes for KID.

In this case I might also refer to [Chambon et al.](https://arxiv.org/abs/2211.12737), which experimented with different network backends than InceptionV3, as there are ongoing discussions on the legitimacy of evaluating medical data on a ImageNet pre-trained network.

Cheers,
Tobias

**Comment by ahmed1996said** [comment]
Thanks for the prompt response, @saiboxx!

Understood, thanks for the clarification. I've noticed that Chambon et al. computed the FID on different backends, including a DenseNet pretrained on X-ray images, which may be more fitting.

In your paper, regarding the FID mentioned in section 5, was it computed using the XRV DenseNet or Inception features?

**Comment by saiboxx** [comment]
I used the implementation in the torchmetrics package, which afaik only offers the standard InceptionV3 backend :+1:

**Comment by ahmed1996said** [comment]
Got it, totally missed that in your previous response sorry! 

Thanks a lot :)
